apiVersion: v1
kind: Secret
metadata:
    name: inventrack-secrets
    namespace: conjunta-desarrollo-seguro
type: Opaque
stringData:
    DB_PASSWORD: "password"
    JWT_SECRET: "jwt_secret"
    GROQ_API_KEY: "groq_api_key"
